@echo off
cls
echo **************************************************************
echo *   Batch program to print Wars of Napoleon documentation    *
echo **************************************************************
echo ÿ
pause Press a key to print Wars of Napoleon Strategy Level Documentation
type won.doc > lpt1
cls
pause Press a key to print Tactical Module Documentation
type napoleon.doc > lpt1
